import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers"

import HeaderNav from "@/components/Navbar"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className='dark min-h-screen'>
      <body className={inter.className}>
        <div className="flex min-h-screen flex-col overflow-x-none">
          <HeaderNav />
          <Providers>
            {children}
          </Providers>
        </div>
      </body>
    </html>
  );
}
